import { useEffect, useMemo, useRef, useState } from 'react';
import { BookOpen, Plus, Search, Download, Upload, Pencil, Trash2, RotateCcw, ArrowUpFromLine, LibraryBig, LayoutDashboard, X, Check, BookMarked } from 'lucide-react';

type Book = { id:string; title:string; author:string; isbn:string; category:string; status:'Available'|'Issued'; borrower:string; dueDate:string };
const KEY='libraryhub.books.v1';
const sample:Book[]=[
{id:'1',title:'Atomic Habits',author:'James Clear',isbn:'9780735211292',category:'Self Development',status:'Available',borrower:'',dueDate:''},
{id:'2',title:'The Alchemist',author:'Paulo Coelho',isbn:'9780061122415',category:'Fiction',status:'Issued',borrower:'Aarav Sharma',dueDate:'2026-10-20'},
{id:'3',title:'Ikigai',author:'Héctor García & Francesc Miralles',isbn:'9780143130727',category:'Lifestyle',status:'Available',borrower:'',dueDate:''},
{id:'4',title:'Clean Code',author:'Robert C. Martin',isbn:'9780132350884',category:'Technology',status:'Available',borrower:'',dueDate:''},
{id:'5',title:'Wings of Fire',author:'A. P. J. Abdul Kalam',isbn:'9788173711466',category:'Biography',status:'Issued',borrower:'Priya Reddy',dueDate:'2026-10-14'}];
const empty={title:'',author:'',isbn:'',category:'Fiction',status:'Available' as Book['status'],borrower:'',dueDate:''};
function getInitial():Book[]{try{const v=localStorage.getItem(KEY);if(v){const p=JSON.parse(v);if(Array.isArray(p))return p;}}catch{}return sample;}
export default function App(){
 const [books,setBooks]=useState<Book[]>(getInitial),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[modal,setModal]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(empty),[toast,setToast]=useState(''),[view,setView]=useState('Dashboard');
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(books));}catch{setToast('Storage is full. Please export a backup.');}},[books]);
 const available=books.filter(b=>b.status==='Available').length,issued=books.length-available;
 const visible=useMemo(()=>books.filter(b=>[b.title,b.author,b.isbn,b.category,b.borrower].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='All'||b.status===filter)&&(view!=='Issued books'||b.status==='Issued')),[books,query,filter,view]);
 function add(){setEditing(null);setDraft({...empty});setModal(true);}
 function edit(b:Book){setEditing(b.id);setDraft({title:b.title,author:b.author,isbn:b.isbn,category:b.category,status:b.status,borrower:b.borrower,dueDate:b.dueDate});setModal(true);}
 function save(e:React.FormEvent){e.preventDefault();if(!draft.title.trim()||!draft.author.trim())return;if(draft.status==='Issued'&&!draft.borrower.trim()){setToast('Enter a borrower name.');return;}const d={...draft,title:draft.title.trim(),author:draft.author.trim(),borrower:draft.status==='Issued'?draft.borrower.trim():'',dueDate:draft.status==='Issued'?draft.dueDate:''};if(editing){setBooks(bs=>bs.map(b=>b.id===editing?{...b,...d}:b));setToast('Book updated.');}else{setBooks(bs=>[{...d,id:crypto.randomUUID()},...bs]);setToast('Book added.');}setModal(false);}
 function issue(b:Book){if(b.status==='Issued'){setBooks(bs=>bs.map(x=>x.id===b.id?{...x,status:'Available',borrower:'',dueDate:''}:x));setToast('Book marked as returned.');}else{setEditing(b.id);setDraft({title:b.title,author:b.author,isbn:b.isbn,category:b.category,status:'Issued',borrower:'',dueDate:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});setModal(true);}}
 function exportData(){const blob=new Blob([JSON.stringify({app:'LibraryHub',version:1,exportedAt:new Date().toISOString(),books},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`libraryhub-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);setToast('Backup downloaded. Store it somewhere safe.');}
 function importData(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result)),arr=Array.isArray(p)?p:p.books;if(!Array.isArray(arr)||!arr.every((b:any)=>b&&typeof b.id==='string'&&typeof b.title==='string'&&typeof b.author==='string'&&(b.status==='Available'||b.status==='Issued')))throw Error();if(confirm(`Replace current catalogue with ${arr.length} books? Export current data first if needed.`)){setBooks(arr);setToast('Backup restored.');}}catch{setToast('Invalid LibraryHub backup file.');}if(fileRef.current)fileRef.current.value='';};r.readAsText(f);}
 function remove(b:Book){if(confirm(`Delete "${b.title}"?`)){setBooks(bs=>bs.filter(x=>x.id!==b.id));setToast('Book deleted.');}}
 return <div className="layout"><aside className="sidebar"><div className="brand"><span className="brand-icon"><LibraryBig/></span><span><b>LibraryHub</b><small>LIBRARY MANAGER</small></span></div><p className="label">WORKSPACE</p>{['Dashboard','All books','Issued books'].map(v=><button key={v} className={`nav ${view===v?'selected':''}`} onClick={()=>setView(v)}><LayoutDashboard size={17}/>{v}{v==='Issued books'&&<em>{issued}</em>}</button>)}<div className="sidebar-tip"><BookMarked/><b>Your data, your control</b><p>Records are saved in this browser. Export backups regularly.</p><button onClick={exportData}>Back up library ↓</button></div><small className="local">● Local workspace</small></aside>
 <main><header><div><span>Workspace</span>　/　<b>{view}</b></div><span className="badge">● Local data</span></header><section className="content"><div className="intro"><div><p className="eyebrow">YOUR LIBRARY, ORGANIZED</p><h1>{view==='Issued books'?'Issued books':view==='All books'?'Book catalogue':'Good to see you, Admin'}<i>.</i></h1><p className="sub">Manage your collection, track borrowed books, and keep everything organized.</p></div><button className="primary" onClick={add}><Plus size={17}/> Add book</button></div>
 <div className="stats"><article><span className="stat-icon blue"><BookOpen/></span><p>Total books</p><strong>{books.length}</strong><small>In your catalogue</small></article><article><span className="stat-icon green"><Check/></span><p>Available</p><strong>{available}</strong><small>Ready to borrow</small></article><article><span className="stat-icon orange"><ArrowUpFromLine/></span><p>Currently issued</p><strong>{issued}</strong><small>With readers</small></article><article><span className="stat-icon purple"><LibraryBig/></span><p>Categories</p><strong>{new Set(books.map(b=>b.category)).size}</strong><small>Across your collection</small></article></div>
 <section className="panel"><div className="panel-title"><div><h2>{view==='Issued books'?'Currently issued':'Book catalogue'}</h2><p>Manage and track your library collection.</p></div><button className="primary small" onClick={add}><Plus size={15}/> Add a book</button></div><div className="filters"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, author, ISBN..."/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="All">All books</option><option>Available</option><option>Issued</option></select><button className="secondary" onClick={exportData}><Download size={15}/> Export backup</button><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={15}/> Import</button><input hidden ref={fileRef} type="file" accept=".json,application/json" onChange={importData}/></div>
 <div className="table-scroll"><table><thead><tr><th>BOOK TITLE</th><th>ISBN</th><th>CATEGORY</th><th>STATUS</th><th>ISSUED TO / DUE</th><th>ACTIONS</th></tr></thead><tbody>{visible.map(b=><tr key={b.id}><td><div className="book"><span className="cover"><BookOpen size={17}/></span><span><b>{b.title}</b><small>{b.author}</small></span></div></td><td>{b.isbn||'—'}</td><td><span className="category">{b.category}</span></td><td><span className={`status ${b.status.toLowerCase()}`}>● {b.status}</span></td><td>{b.status==='Issued'?<span className="borrower"><b>{b.borrower||'Not set'}</b><small>Due {b.dueDate||'—'}</small></span>:'—'}</td><td><div className="actions"><button title={b.status==='Issued'?'Mark returned':'Issue book'} onClick={()=>issue(b)}>{b.status==='Issued'?<RotateCcw size={15}/>:<ArrowUpFromLine size={15}/>}</button><button title="Edit" onClick={()=>edit(b)}><Pencil size={15}/></button><button title="Delete" onClick={()=>remove(b)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{visible.length===0&&<div className="empty"><Search/><b>No books found</b><p>Try another search or add a book.</p></div>}</div><div className="table-foot">Showing <b>{visible.length}</b> of <b>{books.length}</b> books <span>✓ Saved in this browser</span></div></section>
 <div className="bottom"><section className="panel summary"><h3>Collection overview</h3><p>Availability at a glance</p><div className="bar-label"><span>Available books</span><b>{books.length?Math.round(available/books.length*100):0}%</b></div><div className="bar"><span style={{width:`${books.length?available/books.length*100:0}%`}}/></div><small>🟢 Available: {available}　 🟠 Issued: {issued}</small></section><section className="panel backup"><h3>Backup & restore</h3><p>Download a JSON backup before clearing browser data or changing devices. Import restores your saved catalogue.</p><button className="primary" onClick={exportData}><Download size={15}/> Download backup</button><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={15}/> Restore backup</button></section></div>
 <footer>© {new Date().getFullYear()} LibraryHub <span>Made for your library · Free local-first edition</span></footer></section></main>
 {toast&&<div className="toast"><Check size={17}/>{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">CATALOGUE ENTRY</p><h2>{editing?'Edit book details':'Add a new book'}</h2></div><button type="button" className="x" onClick={()=>setModal(false)}><X/></button></div><div className="fields"><label className="wide">Book title *<input required maxLength={120} autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="e.g. The Great Gatsby"/></label><label>Author *<input required value={draft.author} onChange={e=>setDraft({...draft,author:e.target.value})} placeholder="Author name"/></label><label>ISBN<input value={draft.isbn} onChange={e=>setDraft({...draft,isbn:e.target.value})} placeholder="ISBN number"/></label><label>Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{['Fiction','Non-fiction','Technology','Biography','Self Development','Lifestyle','Science','History','Children','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Book['status']})}><option>Available</option><option>Issued</option></select></label>{draft.status==='Issued'&&<><label>Borrower name *<input required value={draft.borrower} onChange={e=>setDraft({...draft,borrower:e.target.value})} placeholder="Reader name"/></label><label>Due date<input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label></>}</div><div className="modal-actions"><span>* Required</span><button type="button" className="secondary" onClick={()=>setModal(false)}>Cancel</button><button className="primary" type="submit"><Check size={15}/>{editing?'Save changes':'Add book'}</button></div></form></div>}
 </div>;
}